# Generated by Django 5.2.7 on 2025-11-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان عکس')),
                ('image', models.ImageField(upload_to='uploads/gallery/', verbose_name='تصویر')),
                ('is_delete', models.BooleanField(verbose_name='حذف شده / نشده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'تصویر گالری',
            },
        ),
    ]
