# Generated by Django 5.2.7 on 2025-10-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('images', models.ImageField(upload_to='uploads/popular', verbose_name='تصویر بازدید')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
            ],
            options={
                'verbose_name': 'تصویر پر بازدید',
                'verbose_name_plural': 'پر بازدیدها',
            },
        ),
    ]
